language: python
# Only python 27 is working for now
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"

virtualenv:
  system_site_packages: true

before_install:
  - curl http://repo.reverbrain.com/REVERBRAIN.GPG | sudo apt-key add -
  - echo "deb http://repo.reverbrain.com/precise/ current/amd64/" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://repo.reverbrain.com/precise/ current/all/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install elliptics
  - cd fixtures && sudo ./start.sh && cd -

install:
  - pip install -rtests/requirements.txt
  - pip install .

script: python setup.py nosetests

after_success: coveralls
