language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - curl http://repo.reverbrain.com/REVERBRAIN.GPG | sudo apt-key add -
  - echo "deb http://repo.reverbrain.com/precise/ current/amd64/" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://repo.reverbrain.com/precise/ current/all/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install elliptics
  - cd fixtures && sudo ./start.sh

install:
  - pip install -M tox

script: tox
